apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://monitoring.service.consul:9090
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: http://monitoring.service.consul:3100
    isDefault: false
