server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /positions.yml

clients:
  - url: http://monitoring_service_name.service.consul:3100/loki/api/v1/push # Loki server dynamically discovered by Consul    # monitoring_service_name will be replaced in ansible task with var "consul_service_name_of_monitoring_leader" 
  # - url: http://localhost:3100/loki/api/v1/push



scrape_configs:
  - job_name: nginx
    static_configs:
      - targets: [localhost]
        labels:
          job: nginx
          __path__: /var/log/nginx/*.log
  

  - job_name: apache
    static_configs:
      - targets: [localhost]
        labels:
          job: apache
          __path__: /var/log/apache2/*.log

  - job_name: system
    static_configs:
    - targets: [localhost]
      labels:
        job: varlogs
        __path__: /var/log/*log

  - job_name: docker  
    static_configs:
    - targets: [localhost]
      labels:
        job: docker
        __path__: /var/lib/docker/containers/*/*.log
