global:
  scrape_interval: 10s


###
# DYNAMIC FILTERING TARGETS(VMS) BY USING TAGS. FOR EXAMPLE:  (1) YandexCloud:  metric: cpu  (2) rules.yml:  by(instance)  (3) param..{metric="cpu"}
###

scrape_configs:
  - job_name: instances
    yandexcloud_sd_configs:
      - service: compute
        yandex_passport_oauth_token: "y0__xD6j7CRBBjB3RMgz9Oh-BQwj42Vrgi34NW1FNOpHk-f0EiTNDlK2DXc4Q"
    relabel_configs:
      - source_labels: [__meta_yandexcloud_instance_label_service]                                               # get label "service" from YC. 
        target_label: "service"                                                                                  # assign name for existed/new label in Prometheus
        replacement: "$1"                                                                                        # get value of label "service" from every vm and write: 

      - source_labels: [__meta_yandexcloud_instance_public_ip_0]                                                 # get public_ip
        target_label: __address__
        replacement: "$1:9100"
